spring.application.name=FinanceAdvisorApplication

spring.datasource.url=jdbc:postgresql://ep-withered-water-an00p7x0-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_drmA1On7fTMR&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_drmA1On7fTMR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=ZmluYW5jZS1hZHZpc29yLXN1cGVyLXNlY3JldC1rZXktMjAyNi1PUk4=
jwt.expiration=86400000

plaid.client-id=69cb4d06af6f7f000d5060c2
plaid.secret=8a360210293420f61c92bf75b0a6fc
plaid.env=sandbox

ai.service.url= http://127.0.0.1:8000